(()=>{
'use strict';
function getJsPDF(){return window.jspdf&&window.jspdf.jsPDF}
function cleanText(v){return String(v||'').replace(/\u00a0/g,' ').replace(/[ \t]+/g,' ').trim()}
function reportMeta(){const sheet=document.getElementById('generatedReportSheet');if(!sheet)throw new Error('Generate a report first.');const h1=sheet.querySelector('.report-title h1');const sub=sheet.querySelector('.report-title p');return {sheet,title:cleanText(h1&&h1.textContent)||'Gladstone AED Report',subtitle:cleanText(sub&&sub.textContent)}}
function addWrapped(doc,text,x,y,width,size=10,bold=false){doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);const lines=doc.splitTextToSize(cleanText(text),width);for(const line of lines){if(y>10.25){doc.addPage();y=.65}doc.text(line,x,y);y+=size<=9?.16:.19}return y}
function buildPdf(){const JsPDF=getJsPDF();if(!JsPDF)throw new Error('PDF engine is still loading. Close and reopen the app, then try again.');const {sheet,title,subtitle}=reportMeta(),doc=new JsPDF({unit:'in',format:'letter',orientation:'portrait'}),left=.65,width=7.2;let y=.65;
 doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text(title,left,y);y+=.28;doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text(doc.splitTextToSize(subtitle,width),left,y);y+=.42;doc.setDrawColor(18,58,90);doc.setLineWidth(.025);doc.line(left,y-0.12,7.85,y-0.12);
 const summary=sheet.querySelector('section');if(summary){doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text('Executive Summary',left,y);y+=.28;const nodes=[...summary.querySelectorAll('p,.kv,h3,li')];for(const n of nodes){let t=cleanText(n.textContent);if(!t||t==='Executive Summary')continue;const isHead=n.tagName==='H3';y=addWrapped(doc,t,left,y,width,isHead?11:9,isHead);y+=isHead?.05:.02}}
 const sections=[...sheet.querySelectorAll('section.report-box')];for(const sec of sections){doc.addPage();y=.65;const name=cleanText(sec.querySelector('h2')?.textContent)||'AED Detail';y=addWrapped(doc,name,left,y,width,15,true);const meta=cleanText(sec.querySelector('.muted')?.textContent);if(meta){y+=.03;y=addWrapped(doc,meta,left,y,width,9,false)}y+=.12;const children=[...sec.querySelectorAll('h3,.kv,tr')];for(const n of children){let t='';if(n.tagName==='TR')t=[...n.children].map(c=>cleanText(c.textContent)).filter(Boolean).join('  |  ');else t=cleanText(n.textContent);if(!t)continue;const head=n.tagName==='H3';if(head)y+=.08;y=addWrapped(doc,t,left,y,width,head?11:9,head);y+=.02}}
 const pages=doc.getNumberOfPages();for(let p=1;p<=pages;p++){doc.setPage(p);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(100);doc.text('Gladstone Fire / EMS AED Inventory',left,10.55);doc.text('Page '+p+' of '+pages,7.25,10.55);doc.setTextColor(0)}return doc}
function filename(){const {title,subtitle}=reportMeta(),q=(subtitle.match(/Q\d\s+\d{4}/)||[''])[0].replace(/\s+/g,'-').toLowerCase(),base=title.replace(/[^a-z0-9]+/ig,'-').replace(/^-+|-+$/g,'').toLowerCase()||'aed-report';return base+(q?'-'+q:'')+'.pdf'}
async function sharePdf(){const doc=buildPdf(),blob=doc.output('blob'),name=filename(),file=new File([blob],name,{type:'application/pdf'});if(!blob||blob.size<1000)throw new Error('PDF generation failed.');if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title:reportMeta().title,files:[file]});return}const url=URL.createObjectURL(blob);window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),60000)}
function openPdf(){const doc=buildPdf(),blob=doc.output('blob');if(!blob||blob.size<1000)throw new Error('PDF generation failed.');const url=URL.createObjectURL(blob);window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),60000)}
document.addEventListener('click',async e=>{const b=e.target.closest&&e.target.closest('#musterPdf,#musterSharePdf');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const share=b.id==='musterSharePdf',old=b.textContent;b.disabled=true;b.textContent=share?'Preparing PDF…':'Creating PDF…';try{if(share)await sharePdf();else openPdf()}catch(err){if(!err||err.name!=='AbortError')alert(err.message||'Unable to create PDF.')}finally{b.disabled=false;b.textContent=old}},true);
})();