const VERSION='gfd-aed-pwa-v213';
const CORE_CACHE=VERSION+'-core';
const RUNTIME_CACHE=VERSION+'-runtime';
const CORE=['./','./index.html','./lifecycle.html','./version-history.json','./manifest.webmanifest','./pdf-engine-v2.js','./report-builder.js','./report-pdf.css'];
self.addEventListener('install',event=>{self.skipWaiting();event.waitUntil(caches.open(CORE_CACHE).then(cache=>cache.addAll(CORE)));});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==CORE_CACHE&&k!==RUNTIME_CACHE).map(k=>caches.delete(k)));await self.clients.claim();})());});
self.addEventListener('message',event=>{if(event.data&&event.data.type==='SKIP_WAITING')self.skipWaiting();});
async function decorateMainApp(response){if(!response||!response.ok)return response;const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let html=await response.text();const isMainApp=html.includes('<title>Gladstone AED Inventory</title>')&&html.includes('data-v="dash"')&&html.includes('data-v="audit"');if(isMainApp){if(!html.includes('report-pdf.css'))html=html.replace('</head>','<link rel="stylesheet" href="./report-pdf.css?v=95"></head>');if(!html.includes('pdf-engine-v2.js'))html=html.replace('</body>','<script src="./pdf-engine-v2.js?v=191"></script></body>');if(!html.includes('report-builder.js'))html=html.replace('</body>','<script src="./report-builder.js?v=164"></script></body>');}const headers=new Headers(response.headers);headers.delete('content-length');return new Response(html,{status:response.status,statusText:response.statusText,headers});}
async function networkFirst(request){try{const fresh=await fetch(request,{cache:'no-store'});const cache=await caches.open(RUNTIME_CACHE);cache.put(request,fresh.clone());return decorateMainApp(fresh);}catch(err){const cached=(await caches.match(request))||(await caches.match('./index.html'));return decorateMainApp(cached);}}
async function staleWhileRevalidate(request){const cached=await caches.match(request);const update=fetch(request).then(async fresh=>{const cache=await caches.open(RUNTIME_CACHE);try{await cache.put(request,fresh.clone())}catch(e){}return fresh;}).catch(()=>null);return cached||(await update)||Response.error();}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(event.request.mode==='navigate'){event.respondWith(networkFirst(event.request));return;}if(url.origin===self.location.origin&&(url.pathname.endsWith('/pdf-export.js')||url.pathname.endsWith('/pdf-engine-v2.js')||url.pathname.endsWith('/report-builder.js')||url.pathname.endsWith('/report-pdf.css'))){event.respondWith(networkFirst(event.request));return;}if(url.origin===self.location.origin){event.respondWith(staleWhileRevalidate(event.request));return;}event.respondWith(staleWhileRevalidate(event.request));});